export const fixtureLayers = {
  all_candidate_sites: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'C-1',
          Unit_Site: 'Candidate 1',
          Site_typ: 'Interchange',
          layer: 'Crawfordsville',
          Shape_Area: 4046.8564,
          Flood_Zone: 'X',
          Volt_Class: '69kV',
          DevOpe_21: 20,
          GrasHe_71: 80,
        },
        geometry: null,
      },
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'C-2',
          Unit_Site: 'Candidate 2',
          Site_typ: 'Facility',
          layer: 'Greenfield',
          Shape_Area: 8093.7128,
          Flood_Zone: 'AE',
          Volt_Class: '138kV',
          DecFor_41: 50,
          CultCr_82: 50,
        },
        geometry: null,
      },
    ],
  },
  facility_scored: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'F-1',
          Unit_Site: 'Facility 1',
          Site_typ: 'Facility',
          layer: 'Crawfordsville',
          Shape_Area: 12140.5692,
          Flood_Zone: 'X',
          Volt_Class: '69kV',
          sol_s: 0.8,
          slp_s: 0.6,
          trn_s: 0.4,
          evp_s: 0.2,
          dem_s: 0.7,
          fld_s: 1,
          lc_s: 0.5,
          DevLowI_22: 30,
          DecFor_41: 20,
          PasHay_81: 50,
        },
        geometry: null,
      },
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'F-2',
          Unit_Site: 'Facility 2',
          Site_typ: 'Facility',
          layer: 'Greenfield',
          Shape_Area: 16187.4256,
          Flood_Zone: 'AE',
          Volt_Class: '138kV',
          sol_s: 0.4,
          slp_s: 0.7,
          trn_s: 0.8,
          evp_s: 0.3,
          dem_s: 0.6,
          fld_s: 0.5,
          lc_s: 0.9,
          DDevMed_23: 40,
          OpenW_11: 10,
          Barre_31: 50,
        },
        geometry: null,
      },
    ],
  },
  row_scored: {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'R-1',
          Unit_Site: 'ROW 1',
          Site_typ: 'ROW',
          layer: 'Crawfordsville',
          Shape_Area: 20234.282,
          Flood_Zone: 'X',
          Volt_Class: '345kV',
          sol_s: 0.9,
          slp_s: 0.3,
          trn_s: 0.6,
          evp_s: 0.8,
          dem_s: 0.4,
          fld_s: 0.7,
          lc_s: 0.2,
          SShrub_52: 60,
          welan_90: 40,
        },
        geometry: null,
      },
      {
        type: 'Feature',
        properties: {
          SPR_ID: 'R-2',
          Unit_Site: 'ROW 2',
          Site_typ: 'ROW',
          layer: 'LaPorte',
          Shape_Area: 24281.1384,
          Flood_Zone: 'X',
          Volt_Class: '345kV',
          sol_s: 0.1,
          slp_s: 0.2,
          trn_s: 0.9,
          evp_s: 0.4,
          dem_s: 0.2,
          fld_s: 0.1,
          lc_s: 0.8,
          EmerW_95: 100,
        },
        geometry: null,
      },
    ],
  },
};
