export const CRITERIA = [
  {
    key: 'sol_s',
    label: 'Solar radiation',
    short: 'Solar',
    measures: 'Incoming solar irradiance',
    attribute: 'Solar_Mean',
    direction: 'Higher score = more suitable',
    sourceNote: 'Solar irradiance dataset - TODO(confirm)',
    sourceConfirmed: false,
  },
  {
    key: 'slp_s',
    label: 'Slope',
    short: 'Slope',
    measures: 'Terrain steepness; flatter sites score higher',
    attribute: 'SlopeMean',
    direction: 'Higher score = flatter',
    sourceNote: 'DEM-derived',
    sourceConfirmed: true,
  },
  {
    key: 'trn_s',
    label: 'Transmission access',
    short: 'Transmission',
    measures: 'Proximity to nearest transmission line',
    attribute: 'NTran_DIST',
    direction: 'Higher score = more suitable',
    sourceNote: 'Transmission line layer - TODO(confirm)',
    sourceConfirmed: false,
  },
  {
    key: 'evp_s',
    label: 'Evapotranspiration',
    short: 'Evapotranspiration',
    measures: 'Climatic water-demand factor',
    attribute: null,
    direction: 'Higher score = more suitable',
    sourceNote: 'Climate dataset - TODO(confirm)',
    sourceConfirmed: false,
  },
  {
    key: 'dem_s',
    label: 'Elevation / terrain',
    short: 'Elevation',
    measures: 'Elevation suitability',
    attribute: null,
    direction: 'Higher score = more suitable',
    sourceNote: 'DEM - TODO(confirm)',
    sourceConfirmed: false,
  },
  {
    key: 'fld_s',
    label: 'Flood risk',
    short: 'Flood',
    measures: 'Flood-zone exposure; less exposure scores higher',
    attribute: 'Flood_Zone, Fld_Area, Fld_Perc',
    direction: 'Higher score = safer',
    sourceNote: 'FEMA flood zones',
    sourceConfirmed: true,
  },
  {
    key: 'lc_s',
    label: 'Land cover',
    short: 'Land cover',
    measures: 'Land-use / land-cover suitability',
    attribute: 'NLCD class fields',
    direction: 'Higher score = more suitable',
    sourceNote: 'NLCD',
    sourceConfirmed: true,
  },
];

export const CRITERIA_BY_KEY = Object.fromEntries(CRITERIA.map((criterion) => [criterion.key, criterion]));
